# Generated by Django 4.2.28 on 2026-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('STK', 'STK Push'), ('C2B', 'C2B')], default='C2B', max_length=10),
        ),
    ]
