# Generated by Django 4.2.28 on 2026-02-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='app_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
